/**
 * Runtime renderer for a single award detail page.
 *
 * The page shell is pre-generated by scripts/build_site.js. At runtime this
 * module fetches the ledger, finds the entry whose index matches the page
 * (extracted from the URL), and renders it using textContent/createElement
 * only â never innerHTML. See scripts/check_xss.py.
 */

import { parseLedger, type LedgerEntry } from "./ledger.js";

const LEDGER_URL = "../GSD-LEDGER.md";

/** Extract the award index from the URL path (e.g. /awards/3.html -> 3). */
function awardIndexFromUrl(): number | null {
  const match = /\/awards\/(\d+)\.html$/.exec(window.location.pathname);
  return match ? Number.parseInt(match[1] ?? "", 10) : null;
}

function dt(label: string, value: string): HTMLDListElement {
  const dl = document.createElement("dl");
  const dt = document.createElement("dt");
  dt.textContent = label;
  const dd = document.createElement("dd");
  dd.textContent = value;
  dl.append(dt, dd);
  return dl;
}

function linkDt(label: string, text: string, href: string | null): HTMLDListElement {
  const dl = document.createElement("dl");
  const dt = document.createElement("dt");
  dt.textContent = label;
  const dd = document.createElement("dd");
  if (href) {
    const a = document.createElement("a");
    a.href = href;
    a.textContent = text;
    dd.append(a);
  } else {
    dd.textContent = text;
  }
  dl.append(dt, dd);
  return dl;
}

function renderAward(entry: LedgerEntry, container: HTMLElement): void {
  container.replaceChildren();

  const title = document.createElement("h2");
  title.textContent = `Award #${entry.index}`;
  container.append(title);

  const grid = document.createElement("div");
  grid.className = "detail-grid";

  grid.append(
    dt("Date", entry.date),
    dt("Contributor", entry.contributor),
    dt("Kind", entry.kind),
    linkDt("Pull Request", entry.pr, entry.prUrl),
    linkDt("Issue", entry.issue, entry.issueUrl),
    dt("Amount", `${entry.amount} ${entry.denomination}`),
    dt("Notes", entry.notes),
  );

  container.append(grid);

  // Link to the contributor's section on the contributors page.
  const contribLink = document.createElement("p");
  const a = document.createElement("a");
  a.href = `../contributors.html#${encodeURIComponent(entry.contributor)}`;
  a.textContent = `See all awards by ${entry.contributor}`;
  contribLink.append(a);
  container.append(contribLink);
}

async function main(): Promise<void> {
  const container = document.querySelector<HTMLElement>("#award-detail");
  const status = document.querySelector<HTMLElement>("#status");
  if (!container || !status) return;

  const index = awardIndexFromUrl();
  if (index === null) {
    status.textContent = "Could not determine which award to display.";
    return;
  }

  try {
    const response = await fetch(LEDGER_URL);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);

    const entries = parseLedger(await response.text());
    const entry = entries.find((e) => e.index === index);

    if (!entry) {
      status.textContent = `Award #${index} was not found in the ledger.`;
      return;
    }

    status.textContent = "";
    renderAward(entry, container);
  } catch (error) {
    status.textContent = `Could not load the ledger: ${
      error instanceof Error ? error.message : "unknown error"
    }`;
  }
}

void main();
